name: bim_ltd
services:
  db:
    env_file:
      - path: .env
        required: true
    image: postgres:15-bookworm
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./logs/db/:/var/log/postgres
    ports:
      - "5432:5432"

  bot:
    build: ../src
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - media:/app/media/
      - static:/app/static/

  nginx:
    image: nginx:latest
    depends_on:
      - bot
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/app/media/
      - static:/app/static/
    ports:
      - "8000:80"

networks:
  default:
    name: bim_ltd_network

volumes:
  db_data:
  media:
  static:
